services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data

  backend:
    image: ${BACKEND_IMAGE_NAME}
    container_name: backend
    restart: always
    volumes:
      - .env:/usr/src/app/.env
    ports:
      - 3000:${PORT}
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
