name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Start PostgreSQL with Docker Compose
        run: docker compose up -d

      - name: Run Prisma migrations
        run: bunx prisma migrate deploy

      - name: Generate Prisma client
        run: bunx prisma generate

      - name: Run tests
        run: bun run test
